### ISSUE TITLE
sass compiler error and missing login entry in menu

### ISSUE THREAD

**Issue by TiloNN** [ub-duisburg-essen/duepublico#14]
There appeared some issues by updating/merging mir.
1. sass blocks build process with an compiler error
2. the login menu entry is missing

`io.bit3.jsass.CompilationException: Error: Custom property values may not be empty.
        on line 103:58 of mir-layout/scss/project_styles/_navigation
        from line 35:9 of mir-layout/scss/flatmir-flatly.scss
>>  nav .navbar-nav .dropdown-menu > li:not(:last-child()) > a {
   ------------------------------------------^
	at io.bit3.jsass.adapter.NativeAdapter.compileString(Native Method)
	at io.bit3.jsass.adapter.NativeAdapter.compile(NativeAdapter.java:55)
	at io.bit3.jsass.Compiler.compile(Compiler.java:114)
	at org.mycore.sass.MCRSassCompilerManager.compile(MCRSassCompilerManager.java:137)`

**Comment by TiloNN** [comment]
GitHub is so smart.
No need to tell you, that I prepared a pull request for you.
So what? Time to talk about this nice weather: Isn't it beautiful today?
